source {C:/Xilinx/10.1/ISE/data/projnav/scripts/VsimStopServer.tcl}
## Auto Generated by Project Navigator to simulate
## HDL Bencher Annotated Test Bench
##
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "Sys_LCDTest.vhd"
vcom -explicit  -93 "LCDTest_tb.ant"
vsim -t 1ps   -lib work LCDTest_tb
run -all
quit -force
