# Project: Evolution3
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = Evolution3.o $(RES)
LINKOBJ  = Evolution3.o $(RES)
LIBS =  -L"lib" -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32  
INCS =  -I"include" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include" 
BIN  = Evolution3.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Evolution3.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Evolution3.exe" $(LIBS)

Evolution3.o: Evolution3.cpp
	$(CPP) -c Evolution3.cpp -o Evolution3.o $(CXXFLAGS)
